<a href="https://colab.research.google.com/github/JoanChege/JoanChege/blob/main/Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#set up the environment
grid_rows = 2
grid_cols = 3
num_actions = 4

#define the reward matrix
rewards = np.array([
    ['S', 1, 0],
    [0, -10, 10]
])


In [ ]:
# Define the Q-Table
q_table = np.zeros((6, 4))

In [ ]:
# Set hyper-parameters
alpha = 0.1  # learning rate
gamma = 0.9  # discount factor
epsilon = 0.1  # exploration rate

In [6]:
# Define the sample environment as a transition matrix
# Each row represents a state, and each column represents an action
# The values in the matrix represent the resulting state when an action is taken from a particular state
# For example, if state 0 takes action 2 (Right), it transitions to state 1
#environment = np.array([[1, 3, 0, 0],  # State 0: Up, Down, Right, Left
                       #[2, 4, 1, 0],  # State 1: Up, Down, Right, Left
                       #[2, 5, 2, 1],  # State 2: Up, Down, Right, Left
                       #[4, 3, 3, 0],  # State 3: Up, Down, Right, Left
                       #[4, 5, 4, 3],  # State 4: Up, Down, Right, Left
                       #[5, 5, 5, 5]]) # State 5: Up, Down, Right, Left

In [9]:
# Q-learning algorithm
for episode in range(num_actions):
    # Reset the environment to the initial state
    state = 0

    # Continue until reaching the goal state (State 5)
    while state != 5:
        # Choose an action using an epsilon-greedy policy
        epsilon = 0.1  # Exploration rate
        if np.random.uniform() < epsilon:
            action = np.random.randint(4)  # Explore
        else:
            action = np.argmax(q_table[state])  # Exploit

        # Perform the chosen action and observe the next state and reward
        next_state = environment[state, action]
        reward = 0 if next_state == 5 else -1  # Reward of -1 for non-goal states

        # Update the Q-value using the Q-learning update rule
        q_table[state, action] += alpha * (reward + gamma * np.max(q_table[next_state]) - q_table[state, action])

        # Transition to the next state
        state = next_state


In [10]:
# Print the learned Q-values
print("Learned Q-values:")
print(q_table)

Learned Q-values:
[[-0.5607541  -0.501859   -0.58519851 -0.58519851]
 [-0.19       -0.271      -0.199      -0.25022796]
 [-0.1         0.          0.          0.        ]
 [-0.271      -0.199      -0.199      -0.34074271]
 [-0.1         0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
